# ------------------------------------------------------------------------------
# appVeyor script
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

version: 1.0.{build}

branches:
  only:
    - test/appveyor1

image: Visual Studio 2013
configuration: Release
platform: x64

clone_depth: 1
clone_folder: c:\build\pgrouting

services:
  - postgresql

#environment:
#  CONFIGURATION: Release

init:
  - git config --global core.autocrlf false

install:
  - cd c:\build
  - curl -O http://download.osgeo.org/postgis/windows/pg94/archive/postgis-bundle-pg94x64-2.2.0.zip
  - 7z x postgis-bundle-pg94x64-2.2.0.zip
  - cd postgis-bundle-pg94x64-2.2.0
  - copy bin\*.dll C:\Progra~1\PostgreSQL\9.4\bin\
  - copy bin\*.exe C:\Progra~1\PostgreSQL\9.4\bin\
  - copy gdaldata C:\Progra~1\PostgreSQL\9.4\
  - copy lib\*.dll C:\Progra~1\PostgreSQL\9.4\lib\
  - copy share\contrib\postgis-2.2 C:\Progra~1\PostgreSQL\9.4\share\contrib\
  - copy share\extension\*.control C:\Progra~1\PostgreSQL\9.4\share\extension\
  - copy share\extension\*.sql C:\Progra~1\PostgreSQL\9.4\share\extension\
  - cd ..
  - curl -O https://github.com/CGAL/cgal/archive/releases/CGAL-4.6.1.zip
  - 7z x CGAL-4.6.1.zip
  - mkdir gmp
  - cd gmp
  - curl -O https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/GMP/5.0.1/gmp-all-CGAL-3.9.zip
  - 7z x gmp-all-CGAL-3.9.zip
  - curl -O https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/MPFR/3.0.0/mpfr-all-CGAL-3.9.zip
  - 7z x mpfr-all-CGAL-3.9.zip

build_script:
  - cd c:\build\pgrouting\tools\windows
  - msbuild_pgrouting.bat 9.4 x64
  - cd c:\build\pgrouting\build\pg94\x64
  - msbuild PGROUTING.sln /target:Build /property:Configuration=%CONFIGURATION%
  - msbuild INSTALL.vcxproj /target:Build /property:Configuration=%CONFIGURATION%
  - copy c:\build\gmp\x64\lib\*.dll C:\Progra~1\PostgreSQL\9.4\bin\

test_script:
  - C:\cygwin64\Cygwin.bat
  - export PGUSER=postgres
  - export PGPASSWORD=Password12!
  - export PGHOME="/cygdrive/c/Progra~1/PostgreSQL/9.4"
  - export PGPORT=9464
  - export PATH=$PATH:$PGHOME/bin
  - cd /cygdrive/c/build/pgrouting
  - tools/testers/algorithm-tester.pl -psql "/cygdrive/c/Progra~1/PostgreSQL/9.4/bin/psql" -ignorenotice
