# ------------------------------------------------------------------------------
# appVeyor script
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

version: 1.0.{build}

branches:
  only:
    - test/appveyor1

image: Visual Studio 2013
configuration: Release
platform: x64

clone_depth: 1
clone_folder: c:\build\pgrouting

services:
  - postgresql94

#environment:
#  CONFIGURATION: Release

init:
  - git config --global core.autocrlf false

install:
  - cd c:\build
  - curl -L http://download.osgeo.org/postgis/windows/pg94/archive/postgis-bundle-pg94x64-2.2.0.zip > postgis-bundle-pg94x64-2.2.0.zip
  - 7z x postgis-bundle-pg94x64-2.2.0.zip
  - xcopy /e /y postgis-bundle-pg94x64-2.2.0 C:\Progra~1\PostgreSQL\9.4
  - curl -L http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.zip > boost_1_58_0.zip
  - 7z x boost_1_58_0.zip
  - curl -L http://github.com/CGAL/cgal/archive/releases/CGAL-4.6.1.zip > CGAL-4.6.1.zip
  - 7z x CGAL-4.6.1.zip
  - mkdir gmp\x64
  - cd gmp\x64
  - curl -L http://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/GMP/5.0.1/gmp-all-CGAL-3.9.zip > gmp-all-CGAL-3.9.zip
  - 7z x gmp-all-CGAL-3.9.zip
  - curl -L http://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/MPFR/3.0.0/mpfr-all-CGAL-3.9.zip > mpfr-all-CGAL-3.9.zip
  - 7z x mpfr-all-CGAL-3.9.zip

build_script:
  - cd c:\build\pgrouting\tools\windows
  - msbuild_pgrouting.bat 9.4 x64
  - cd c:\build\pgrouting\build\pg94\x64
  - msbuild PGROUTING.sln /target:Build /property:Configuration=%CONFIGURATION%
  - msbuild INSTALL.vcxproj /target:Build /property:Configuration=%CONFIGURATION%
  - copy c:\build\gmp\x64\lib\*.dll C:\Progra~1\PostgreSQL\9.4\bin\

test_script:
  - C:\cygwin64\Cygwin.bat
  - export PGUSER=postgres
  - export PGPASSWORD=Password12!
  - export PGHOME="/cygdrive/c/Progra~1/PostgreSQL/9.4"
  - export PGPORT=5432
  - export PATH=$PATH:$PGHOME/bin
  - cd /cygdrive/c/build/pgrouting
  - tools/testers/algorithm-tester.pl -psql "/cygdrive/c/Progra~1/PostgreSQL/9.4/bin/psql" -ignorenotice
